<?php
/**
 * This template displays the Product Category and Tag taxonomy term archives
 *
 * @package genesis_connect_woocommerce
 * @version 0.9.8
 *
 * Note for customisers/users: Do not edit this file!
 * ==================================================
 * If you want to customise this template, copy this file (keep same name) and place the
 * copy in the child theme's woocommerce folder, ie themes/my-child-theme/woocommerce
 * (Your theme may not have a 'woocommerce' folder, in which case create one.)
 * The version in the child theme's woocommerce folder will override this template, and
 * any future updates to this plugin won't wipe out your customisations.
 *
 */

/** Remove default Genesis loop */
remove_action( 'genesis_loop', 'genesis_do_loop' );

/** Remove WooCommerce breadcrumbs */
remove_action( 'woocommerce_before_main_content', 'woocommerce_breadcrumb', 20 );

/** Uncomment the below line of code to add back WooCommerce breadcrumbs */
//add_action( 'genesis_before_loop', 'woocommerce_breadcrumb', 10, 0 );

/** Remove Woo #container and #content divs */
remove_action( 'woocommerce_before_main_content', 'woocommerce_output_content_wrapper', 10 );
remove_action( 'woocommerce_after_main_content', 'woocommerce_output_content_wrapper_end', 10 );


/**
 * Enqueue single page script accordion.js
 *
 * @return void
 */
add_action( 'wp_enqueue_scripts', function () {

	if ( is_product_taxonomy() ) {

		wp_enqueue_script( 'equal-height-js', get_stylesheet_directory_uri() . '/dist/js/packages/equal-height.js', [ 'jquery' ], CHILD_THEME_VERSION, true );

		wp_enqueue_script( 'equal-height-init-js', get_stylesheet_directory_uri() . '/dist/js/single/equal-height-init.js', [
				'equal-height-js',
				'jquery'
			], CHILD_THEME_VERSION, true );

		wp_enqueue_script( 'backstretch-cat', get_stylesheet_directory_uri() . '/dist/js/packages/jquery.backstretch.min.js', [ 'jquery' ], '2.0.4', true );

		wp_enqueue_script( 'backstretch-set-product-category-js', get_stylesheet_directory_uri() . '/dist/js/single/backstretch-set-product-category.js', [
				'jquery',
				'backstretch-cat'
			], CHILD_THEME_VERSION, true );

	}
} );


add_action( 'genesis_after_header', 'check_inn_systems_show_prod_cat_image_as_bg', 11 );
function check_inn_systems_show_prod_cat_image_as_bg() {
	if ( is_product_taxonomy() ) {

		$test = get_queried_object();
		$queried_object = get_queried_object_id();
		$product_hero   = get_field( 'hero_image', 'product_cat_' . $queried_object );

		wp_localize_script( 'backstretch-set-product-category-js', 'BackStretchImgUrl', [
				'hero_src' => $product_hero['url'],
			] ); ?>

		<section class = "product-cat-hero"
		         style = "background: url( <?php echo $product_hero['url'] ?> ) no-repeat;">
			<div class = "wrap">

				<?php
				echo '<h1 class="product-cat-heading">' . $test->name . '</h1>';
				?>


			</div>
		</section>

		<?php

	}
}

add_filter( 'woocommerce_show_page_title', '__return_false' );
//add_action( 'woocommerce_archive_description', 'woocommerce_taxonomy_archive_description' );



//Removes Title and Description on Archive, Taxonomy, Category, Tag
remove_action( 'genesis_before_loop', 'genesis_do_taxonomy_title_description', 15 );

add_action( 'genesis_loop', 'genesiswooc_product_taxonomy_loop' );
/**
 * Displays shop items for the queried taxonomy term
 *
 * This function has been refactored in 0.9.4 to provide compatibility with
 * both WooC 1.6.0 and backwards compatibility with older versions.
 * This is needed thanks to substantial changes to WooC template contents
 * introduced in WooC 1.6.0.
 *
 * @uses genesiswooc_content_product() if WooC is version 1.6.0+
 * @uses genesiswooc_product_taxonomy() for earlier WooC versions
 *
 * @since 0.9.0
 * @updated 0.9.4
 */
function genesiswooc_product_taxonomy_loop() {

	global $woocommerce;

	$new = version_compare( $woocommerce->version, '1.6.0', '>=' );

	if ( $new )
		genesiswooc_content_product();

	else
		genesiswooc_product_taxonomy();

}

genesis();
